@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam sequence {
'ArrowColor DeepSkyBlue
'ActorBorderColor DeepSkyBlue
'LifeLineBorderColor blue
'LifeLineBackgroundColor #A9DCDF

'ParticipantBorderColor DeepSkyBlue
ParticipantBackgroundColor white
'ParticipantFontName Impact
'ParticipantFontSize 17
'ParticipantFontColor #A9DCDF

ActorBackgroundColor white
'ActorFontColor DeepSkyBlue
'ActorFontSize 17
'ActorFontName Aapex
}

actor 用户 as user
participant 工资服务 as salary
participant 结算单 as settle
'participant 打款单 as finance


user -> salary: 发起提现

salary -> settle: 结算单发起结算
'alt 失败
    salary <[#red]-- settle: error
    user <[#red]-- salary: 提现失败，请重试
'else 成功
'    salary <-- settle: response
'    salary -> salary: 记录结算单状态
'
'    salary -[#blue]> finance: 直接打款
'    salary <-- finance: 打款单id
'
'    salary -> salary: 保存打款单id，记录状态
'
'    user <-- salary: 提现成功
'
'end


@enduml